from m_hunter.core.finding import Finding
from m_hunter.core.target import Target
from m_hunter.scanners.base import BaseScanner


class ExampleScanner(BaseScanner):
    name = "example"
    description = "Example scanner for testing the scanner architecture"

    def run(self, target: Target) -> list[Finding]:
        finding = Finding(
            title="Example Finding",
            severity="Info",
            confidence="High",
            target=target.url,
            description="This is a test finding generated by the example scanner.",
            evidence="Example scanner executed successfully.",
            remediation="No action required."
        )

        return [finding]
